defaults:
  - scope:
      path: index
    values:
      layout: default
kramdown:
  auto_ids: false
livereload: true
sass:
  implementation: sass-embedded
  sass_dir:       assets/styles
  sourcemap:      never
theme: null
